services:
  - type: web
    name: code-server-ruby-hack-challenge
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      - key: PASSWORD
        sync: false

