services:
  - type: web
    name: code-server-ruby-hack-challenge
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      - key: PASSWORD
        sync: false

    disk:
      - name: code_data
        mountPath: /data
        sizeGB: 5
      - name: workspace
        mountPath: /workspace
        sizeGB: 5
